//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="SoapServer", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="SoapServer", ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: SoapServer 네임스페이스의 요소 이름 HelloWorldResult이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="SoapServer/HelloWorld", ReplyAction="*")]
        SoapClient.ServiceReference1.HelloWorldResponse HelloWorld(SoapClient.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SoapServer/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync(SoapClient.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SoapServer/Count", ReplyAction="*")]
        int Count();
        
        [System.ServiceModel.OperationContractAttribute(Action="SoapServer/Count", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CountAsync();
        
        // CODEGEN: SoapServer 네임스페이스의 요소 이름 name이(가) "nillable"로 표시되지 않았으므로 메시지 계약을 생성합니다.
        [System.ServiceModel.OperationContractAttribute(Action="SoapServer/GetCurrentors", ReplyAction="*")]
        SoapClient.ServiceReference1.GetCurrentorsResponse GetCurrentors(SoapClient.ServiceReference1.GetCurrentorsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SoapServer/GetCurrentors", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapClient.ServiceReference1.GetCurrentorsResponse> GetCurrentorsAsync(SoapClient.ServiceReference1.GetCurrentorsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SoapServer/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="SoapServer/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="SoapServer/Sub", ReplyAction="*")]
        int Sub(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="SoapServer/Sub", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="SoapServer/Div", ReplyAction="*")]
        int Div(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="SoapServer/Div", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DivAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="SoapServer/Mul", ReplyAction="*")]
        int Mul(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="SoapServer/Mul", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MulAsync(int a, int b);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="SoapServer", Order=0)]
        public SoapClient.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SoapClient.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="SoapServer", Order=0)]
        public SoapClient.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SoapClient.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SoapServer")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentorsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentors", Namespace="SoapServer", Order=0)]
        public SoapClient.ServiceReference1.GetCurrentorsRequestBody Body;
        
        public GetCurrentorsRequest() {
        }
        
        public GetCurrentorsRequest(SoapClient.ServiceReference1.GetCurrentorsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SoapServer")]
    public partial class GetCurrentorsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetCurrentorsRequestBody() {
        }
        
        public GetCurrentorsRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentorsResponse", Namespace="SoapServer", Order=0)]
        public SoapClient.ServiceReference1.GetCurrentorsResponseBody Body;
        
        public GetCurrentorsResponse() {
        }
        
        public GetCurrentorsResponse(SoapClient.ServiceReference1.GetCurrentorsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SoapServer")]
    public partial class GetCurrentorsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapClient.ServiceReference1.ArrayOfString GetCurrentorsResult;
        
        public GetCurrentorsResponseBody() {
        }
        
        public GetCurrentorsResponseBody(SoapClient.ServiceReference1.ArrayOfString GetCurrentorsResult) {
            this.GetCurrentorsResult = GetCurrentorsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : SoapClient.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<SoapClient.ServiceReference1.WebServiceSoap>, SoapClient.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapClient.ServiceReference1.HelloWorldResponse SoapClient.ServiceReference1.WebServiceSoap.HelloWorld(SoapClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SoapClient.ServiceReference1.HelloWorldRequest inValue = new SoapClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SoapClient.ServiceReference1.HelloWorldRequestBody();
            SoapClient.ServiceReference1.HelloWorldResponse retVal = ((SoapClient.ServiceReference1.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapClient.ServiceReference1.HelloWorldResponse> SoapClient.ServiceReference1.WebServiceSoap.HelloWorldAsync(SoapClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            SoapClient.ServiceReference1.HelloWorldRequest inValue = new SoapClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SoapClient.ServiceReference1.HelloWorldRequestBody();
            return ((SoapClient.ServiceReference1.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Count() {
            return base.Channel.Count();
        }
        
        public System.Threading.Tasks.Task<int> CountAsync() {
            return base.Channel.CountAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapClient.ServiceReference1.GetCurrentorsResponse SoapClient.ServiceReference1.WebServiceSoap.GetCurrentors(SoapClient.ServiceReference1.GetCurrentorsRequest request) {
            return base.Channel.GetCurrentors(request);
        }
        
        public SoapClient.ServiceReference1.ArrayOfString GetCurrentors(string name) {
            SoapClient.ServiceReference1.GetCurrentorsRequest inValue = new SoapClient.ServiceReference1.GetCurrentorsRequest();
            inValue.Body = new SoapClient.ServiceReference1.GetCurrentorsRequestBody();
            inValue.Body.name = name;
            SoapClient.ServiceReference1.GetCurrentorsResponse retVal = ((SoapClient.ServiceReference1.WebServiceSoap)(this)).GetCurrentors(inValue);
            return retVal.Body.GetCurrentorsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapClient.ServiceReference1.GetCurrentorsResponse> SoapClient.ServiceReference1.WebServiceSoap.GetCurrentorsAsync(SoapClient.ServiceReference1.GetCurrentorsRequest request) {
            return base.Channel.GetCurrentorsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapClient.ServiceReference1.GetCurrentorsResponse> GetCurrentorsAsync(string name) {
            SoapClient.ServiceReference1.GetCurrentorsRequest inValue = new SoapClient.ServiceReference1.GetCurrentorsRequest();
            inValue.Body = new SoapClient.ServiceReference1.GetCurrentorsRequestBody();
            inValue.Body.name = name;
            return ((SoapClient.ServiceReference1.WebServiceSoap)(this)).GetCurrentorsAsync(inValue);
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public int Sub(int a, int b) {
            return base.Channel.Sub(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SubAsync(int a, int b) {
            return base.Channel.SubAsync(a, b);
        }
        
        public int Div(int a, int b) {
            return base.Channel.Div(a, b);
        }
        
        public System.Threading.Tasks.Task<int> DivAsync(int a, int b) {
            return base.Channel.DivAsync(a, b);
        }
        
        public int Mul(int a, int b) {
            return base.Channel.Mul(a, b);
        }
        
        public System.Threading.Tasks.Task<int> MulAsync(int a, int b) {
            return base.Channel.MulAsync(a, b);
        }
    }
}
